apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-basic-169927474
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/y0jhqlud-tenant/test-app-169927474/python-basic-169927474@sha256:09fa384ebfe223114ae4cb19e3d30dda61ff80537168cad704092dd467f3f4ce
        name: my-python
        resources: {}
status: {}
